name: docker

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set lowercase repository name
      run: |
        echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
      env:
        REPOSITORY: '${{ github.repository }}'
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Github registry
      uses: docker/login-action@v1 
      with:
        username: ${{ github.actor }}
        password:  ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    
    - uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ env.REPOSITORY_LC }}:multiarch
